### ISSUE TITLE
Fragment shader errors while compiling

### ISSUE THREAD

**Issue by ilendemli** [jaredloomis/YFNH-LWJGL#1]
Fragment shader wasn't able to be compiled correctly. Error log:
ERROR: 0:11: 'varying' : cannot be int 
ERROR: 0:31: '=' :  cannot convert from '4-component vector of float' to '3-component vector of float'
ERROR: 0:46: 'assign' :  cannot convert from 'float' to '3-component vector of float'
ERROR: 0:49: 'texID' : int/uint varying is not flat interpolated 
ERROR: 0:57: 'texID' : int/uint varying is not flat interpolated 
WARNING: 0:57: 'texture' : function not available in current GLSL version - trying implict argument conversion 
ERROR: 0:57: 'texture' : no matching overloaded function found (using implicit conversion)

**Comment by jaredloomis** [comment]
This repository is outdated. The newest one is at [My other repository](https://github.com/fiendfan1/Your_Future_Needs_Help).
That being said, I am not maintaining/further developing either at this point.

**Comment by ilendemli** [comment]
Thank you anyway, I learned alot from your code!
